### PR TITLE
Refactor with tests

### PR DESCRIPTION
**Pull request by BrentonPoke**
Not a real refactor, but did prepare a couple of beans for v2 of the API. The v1 methods should still be fine.

### CODE REVIEW

**Comment by skamoen** [comment]
Hey Brenton,
Nice to see you're still working on this! Your code looks good, but I don't have time to test this until after next week. I've enabled Travis for this repo, so a new git push should trigger a build so you can test that.

**Comment by BrentonPoke** [comment]
I have Travis pointed at my fork, and the tests I have pass. I don't have tests for the creation or deletion of tournaments yet, but I want to try to mock them later.
BuildStatus

**Comment by BrentonPoke** [comment]
So that last CI check failed because I'm having issues with gradle and the "classpath". Since I deal mainly with maven, I don't know why it can't find all the dependencies I've listed, but the tests themselves are fine. Any chance we could switch to maven? I don't really know what i'm doing with gradle and intelliJ isn't much help.

**Comment by skamoen** [comment]
Maven dependencies are very easily converted to gradle dependencies. The error is quite straightforward:
`> Could not find junit:junit:5.`
Which means there's no such package on maven.org, as the latest version is 4.12 (http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22junit%22%20AND%20a%3A%22junit%22)

(also, you don't need junit as both compile and testcompile, just the testcompile will do)

I think junit5 moved to a new package name, so this might work: https://mvnrepository.com/artifact/org.junit/junit5-api/5.0.0-ALPHA
```
// https://mvnrepository.com/artifact/org.junit/junit5-api
compile group: 'org.junit', name: 'junit5-api', version: '5.0.0-ALPHA'
```
For future reference, just look up your dependency here: https://mvnrepository.com/ and copy stuff from the gradle tab. It's not all that more complicated than maven 😉

**Comment by BrentonPoke** [comment]
I'll try to re-push with the edits.

**Comment by skamoen** [comment]
It seems you need this for JUnit5, not the one I linked before: https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api

**Comment by BrentonPoke** [comment]
IntelliJ doesn't seem to know where the jars are after gradle imports them, assuming they were imported.

**Comment by BrentonPoke** [comment]
So i forgot to tell you that you have to set environment variables in travis for the tests to pass. Mine do, and they're my toornament CLIENT, SECRET and KEY credentials. The tests pull them from the environment on my own system as well, and it's been working out well for me.

The tests all passed on my travis run.
passed!

**Comment by BrentonPoke** [comment]
Any chance we can get this merged in soon?

**Comment by skamoen** [comment]
Unfortunately I really don't have the time to look at this properly. I'm not sure if that will change in the near future as it's not clear if we'll be using this for our project, so I don't think it's fair towards you to be dependent on me.

As you already have your fork working, I suggest you continue development there and just do your things without waiting for my approval/reviews. That way, you also don't have to follow the standards I set (formatting, Gradle/Maven, etc) and you can just implement things your way.

You're absolutely free to use and modify the code I've written so far, as long as you keep my original commits part of the history.

**Comment by BrentonPoke** [comment]
Well, I made a separate repo for myself, since there's no way to break fork relations. It's at https://github.com/BrentonPoke/ToornamentClient and you're still in the commit history.

**Comment by BrentonPoke** [comment]
@skamoen By the way, do you mind if I relicense my fork to Apache2 while keeping your copyright. I don't like patent trolls.

**Comment by TimvdLippe** [comment]
We are not legal experts, so please contact a lawyer to be certain. In any case, all source code that we authored and exists in this repository must be accompanied by our license. You are not allowed to modify our license. (Still it is MIT, so you are free to create extensions of the source code)

**Comment by BrentonPoke** [comment]
@TimvdLippe I think you're confusing license and copyright. The copyright will always be there, the license is the MIT license and can't be modified, only replaced. In this case, it'd be the friendlier Apache 2.

**Comment by BrentonPoke** [comment]
@TimvdLippe I think you're confusing license with copyright.

**Comment by martijnjanssen** [comment]
The way this works is the following:
All the code that is in this repository has to remain under this license. Any code from this repo that remains in your repository has to have the MIT license. This license cannot be changed. Only the original copyrightholder of the code is allowed to change the license of this repository. All the files and code from this repository must hold the original license (MIT).

Any code that you are adding at a later point in your own repository, you are allowed to use another license that is compatible with the MIT license. You are the copyrightholder for that code and are allowed to modify the license for.

**Comment by BrentonPoke** [comment]
Yeah, I know how it works, which is why I was hoping you guys would change the license to apache 2 for the patent trolling protections. The MIT license is OK, it just doesn't have any "don't be a dick" clauses.

**Comment by TimvdLippe** [comment]
We have no plans in the near future to change our license.

**Pull request closed without merging**
