### PR TITLE
Added a getter to make getAccessToken() work, implemented getTourname…

### PR DESCRIPTION
**Pull request by BrentonPoke**
…nt(String id)

I haven't yet written my application to test these facilities, but I'm pretty sure they work.

### CODE REVIEW

**Comment by skamoen** [comment]
First of all, thanks for the PR! The github diff is a bit messed up (tabs vs space perhaps?), but this seems a good place to start expanding. 

We're using [Lombok](https://projectlombok.org/) for our getters and setters (That's what the `@Data` is for), but I'm not sure if this works in a project without that enabled, so separate getters and setters may need to be defined explicitly. 

I'll get back to you with a way of applying a coherent code style and I'll test if Lombok is usable or if we need the getter/setter boilerplate.

**Comment by BrentonPoke** [comment]
Oh, I didn't know they were generated. I've never heard of or used Lombok, but line 31 in the original holds what's essentially an empty getter that I need to work for my own project.

**Comment by skamoen** [comment]
Could you try and rebase this? I think my latest commits solved a number of issues in this PR

**Comment by BrentonPoke** [comment]
I'm still new to pull requests, so I just recloned and will start again from where you committed.

**Pull request closed without merging**
